const mockCompanies = [
  {
    id: 'eh-emprender',
    companyName: 'EH Emprender',
    companyDescription: 'Empresa del barrio',
    companyCategories: ['Moda', 'Comida'],
    companyPhone: '3001234567',
    companyWebPage: 'https://www.ehemprender.com',
    companySocialNetworks: {
      facebook: 'https://facebook.com/ehemprender',
      instagram: 'https://instagram.com/ehemprender',
      x: '',
      tiktok: '',
      linkedin: '',
    },
  },
  {
    id: 'barrio-vivo',
    companyName: 'Barrio Vivo',
    companyDescription: 'Emprendimiento local con productos artesanales',
    companyCategories: ['Artesanías', 'Hogar'],
    companyPhone: '3017654321',
    companyWebPage: 'https://www.barriovivo.co',
    companySocialNetworks: {
      facebook: '',
      instagram: 'https://instagram.com/barriovivo',
      x: '',
      tiktok: '',
      linkedin: '',
    },
  },
  {
    id: 'la-esquina-creativa',
    companyName: 'La Esquina Creativa',
    companyDescription: 'Tienda de diseño y accesorios del sector',
    companyCategories: ['Moda', 'Accesorios'],
    companyPhone: '3029876543',
    companyWebPage: '',
    companySocialNetworks: {
      facebook: '',
      instagram: '',
      x: '',
      tiktok: '',
      linkedin: '',
    },
  },
  {
    id: 'sabores-de-casa',
    companyName: 'Sabores de Casa',
    companyDescription: 'Negocio familiar de comida típica y postres',
    companyCategories: ['Comida', 'Repostería'],
    companyPhone: '3154567890',
    companyWebPage: '',
    companySocialNetworks: {
      facebook: '',
      instagram: '',
      x: '',
      tiktok: '',
      linkedin: '',
    },
  },
  {
    id: 'mercado-comunidad',
    companyName: 'Mercado Comunidad',
    companyDescription: 'Plataforma de productos locales y servicios vecinales',
    companyCategories: ['Servicios', 'Tecnología'],
    companyPhone: '3201239876',
    companyWebPage: 'https://www.mercadocomunidad.com',
    companySocialNetworks: {
      facebook: '',
      instagram: '',
      x: '',
      tiktok: '',
      linkedin: 'https://linkedin.com/company/mercado-comunidad',
    },
  },
];

export default mockCompanies;
